# -*- coding: utf-8 -*-
"""ASS1.casestudy1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRnuR6Nf_TLPsFX4Qm0csTxDoX8kWKKQ
"""

# Battery sensor data
battery_data = [
    [0, 32, 400, 20, 95],
    [1, 35, 395, 22, 88],
    [2, 38, 390, 25, 80],
    [3, 40, 385, 28, 70],
    [4, 42, 380, 30, 60],
    [5, 45, 375, 32, 48]
]

# Display all readings
for reading in battery_data:
    print("Time:", reading[0],
          "h, Temperature:", reading[1],
          "°C, Voltage:", reading[2],
          "V, Current:", reading[3],
          "A, Charge:", reading[4], "%")

for reading in battery_data:
    temperature = reading[1]

    if temperature > 40:
        print("Time", reading[0], ":", "High Temperature Alert")
    else:
        print("Time", reading[0], ":", "Temperature Normal")

for reading in battery_data:
    charge = reading[4]

    if charge < 50:
        print("Time", reading[0], ":", "Low Battery Alert")
    else:
        print("Time", reading[0], ":", "Battery Charge Normal")

def battery_status(charge):
    if charge > 70:
        return "High"
    elif charge >= 50:
        return "Medium"
    else:
        return "Low"


# Test the function
for reading in battery_data:
    charge = reading[4]
    print("Time:", reading[0], "h ->", battery_status(charge))

TASK2

import numpy as np

D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

print(D)

print(D.shape)

averages = np.mean(D, axis=0)

print("Average Temperature:", averages[0])
print("Average Voltage:", averages[1])
print("Average Current:", averages[2])
print("Average Charge:", averages[3])

temperature = D[:, 0]

print("Maximum Temperature:", np.max(temperature))
print("Minimum Temperature:", np.min(temperature))

voltage = D[:, 1]

print(voltage)

high_temperature = D[D[:, 0] > 40]

print(high_temperature)

low_battery = D[D[:, 3] < 50]

print(low_battery)

A = np.array([
    [2, 1],
    [1, 3]
])

X = np.array([
    [40],
    [25]
])

Y = A @ X

print("Y =")
print(Y)

A_transpose = A.T
print(A_transpose)

det_A = np.linalg.det(A)
print(det_A)

A_inverse = np.linalg.inv(A)
print(A_inverse)

A = np.array([
    [2, 1],
    [1, 3]
])

B = np.array([100, 120])

solution = np.linalg.solve(A, B)

print("x =", solution[0])
print("y =", solution[1])

