# -*- coding: utf-8 -*-
"""ASS2.case study2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AP5nvxtsJ1Y8c_JbRc5XBnpaUzpvT-9t
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = {
    "Student": ["S1", "S2", "S3", "S4", "S5",
                "S6", "S7", "S8", "S9", "S10"],

    "Study_Hours": [2, 3, 4, 5, 6, 7, 8, 4, 6, 9],

    "Attendance": [65, 70, 75, 80, 85, 90, 92, 78, 88, 95],

    "Assignment_Score": [55, 60, 65, 72, 78, 85, 88, 70, 80, 92],

    "Previous_Score": [58, 62, 68, 70, 76, 82, 86, 72, 79, 90],

    "Final_Score": [60, 64, 70, 75, 82, 88, 91, 74, 84, 94]
}

df = pd.DataFrame(data)

print(df)

print("Number of students:", len(df))

print("Column names:")
print(df.columns)

print(df.dtypes)

print(df.head())

print(df.tail())

print(df.info())

part B

print("Complete Dataset:")
print(df)

print(df[[
    "Study_Hours",
    "Attendance",
    "Assignment_Score",
    "Previous_Score",
    "Final_Score"
]].mean())

highest = df.loc[df["Final_Score"].idxmax()]
print(highest)

lowest = df.loc[df["Final_Score"].idxmin()]
print(lowest)

print(df[df["Attendance"] > 80])

print(df[df["Final_Score"] > 80])

print(df.describe())

part C

final_scores = df["Final_Score"].to_numpy()

print(final_scores)

print("Mean:", np.mean(final_scores))

print("Median:", np.median(final_scores))

print("Maximum:", np.max(final_scores))

print("Minimum:", np.min(final_scores))

print("Standard Deviation:", np.std(final_scores))

part D

plt.figure(figsize=(7, 5))

plt.scatter(df["Study_Hours"], df["Final_Score"],
            color="blue", s=80)

plt.xlabel("Study Hours")
plt.ylabel("Final Score")
plt.title("Study Hours vs Final Score")
plt.grid(True)

plt.show()

plt.figure(figsize=(7, 5))

plt.scatter(df["Attendance"], df["Final_Score"],
            color="green", s=80)

plt.xlabel("Attendance (%)")
plt.ylabel("Final Score")
plt.title("Attendance vs Final Score")
plt.grid(True)

plt.show()

plt.figure(figsize=(7, 5))

plt.hist(df["Final_Score"],
         bins=5,
         color="orange",
         edgecolor="black")

plt.xlabel("Final Score")
plt.ylabel("Number of Students")
plt.title("Distribution of Final Scores")

plt.show()

plt.figure(figsize=(8, 5))

plt.bar(df["Student"], df["Final_Score"],
        color="purple")

plt.xlabel("Student")
plt.ylabel("Final Score")
plt.title("Student-wise Final Scores")

plt.show()

PART E

X = df[[
    "Study_Hours",
    "Attendance",
    "Assignment_Score"
]].values

print("X:")
print(X)

print("Shape:", X.shape)

print("Transpose:")
print(X.T)

print("X transpose X:")
print(X.T @ X)

study_hours = df["Study_Hours"].values
final_scores = df["Final_Score"].values

dot_product = np.dot(study_hours, final_scores)

print("Dot Product:", dot_product)

PART f

def F(x):
    return 40 + 5*x - 0.2*x**2

def dF(x):
    return 5 - 0.4*x

for x in range(1, 11):
    print(x, F(x), dF(x))

PART G

def L(x):
    return 5*x - 0.2*x**2

x_values = np.linspace(0, 5, 1000)
y_values = L(x_values)

area = np.trapezoid(y_values, x_values)

print("Numerical integral:", area)

PART H

correlation_matrix = df.corr(numeric_only=True)

print(correlation_matrix)

plt.figure(figsize=(9, 6))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")
plt.show()

